version: '1.0'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres.iitsjkydynxmyoksdtlh
      - POSTGRES_PASSWORD=BinarfudSynrgy7
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.iitsjkydynxmyoksdtlh&password=BinarfudSynrgy7
      - SPRING_DATASOURCE_USERNAME=postgres.iitsjkydynxmyoksdtlh
      - SPRING_DATASOURCE_PASSWORD=BinarfudSynrgy7
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - 8086:8086

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres.iitsjkydynxmyoksdtlh
      - POSTGRES_PASSWORD=BinarfudSynrgy7
      - POSTGRES_DB=binarfud
    ports:
      - 6543:6543